### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by christopheblin** [nadirbad/VerticalSliceArchitecture#2]
Of all examples about VSA on the internet, I found this one to be the most relevant (at least from my POV, obviously), so thank you for this !

My only question is why do you use Mediator ?

Otherwise said, what is the benefit of Mediator instead of directly implementing in the controller (or in a dedicated class but without the IRequestHandler) ?

```
public class ExportTodosController : ApiControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly IMapper _mapper;
    private readonly ICsvFileBuilder _fileBuilder;
    
    [HttpGet("/api/todo-lists/{id}")]
    public async Task<FileResult> Get(int id)
    {
        var records = await _context.TodoItems
                .Where(t => t.ListId == request.ListId)
                .ProjectTo<TodoItemRecord>(_mapper.ConfigurationProvider)
                .ToListAsync(cancellationToken);
        var csv = _fileBuilder.BuildTodoItemsFile(records);

        return File(csv, "text/csv", "TodoItems.csv");
    }
}
```

Doing this you still have testability, isolation from other features / coupling inside the slice, so why bother with an additional technical component ?

**Comment by nadirbad** [comment]
Thank you for your kind words about the VSA example. I appreciate your interest. 

The answer for the usage of MediatR library is personal preference and based on experience of using it on multiple project and teams. It always "depends" on the context, project, requirements. And this solution is an example how it can be done. As you said it can be implemented in the controller or dedicated class without usage of MediatR.

Couple of reasons I personally like it and found it useful:
1. Decoupling your application code from the ASP.NET framework. If you need to use the application logic code, not only from the ASP.NET framework. Not all incoming requests are going to be via HTTP. There may be various ways that interact with your application.
2. Usage of **IPipelineBehavior**, that acts kind of middle-ware and allow to implement some cross-cutting concerns like logging, authorization ... It can be a clean way to separate different concerns
3. It enables publishing events, notification with usage of **INotification**. It can be used for sending email, various notifications and additional logic. It plays nicely if you apply concepts of domain driven design.

I hope my answer, provided you with some more context. And as I said it always depends :)
