### ISSUE TITLE
Project split

### ISSUE THREAD

**Issue by karoldeland** [nadirbad/VerticalSliceArchitecture#4]
Hi @nadirbad, I'm wondering why you have split the code in two projects like API and Application. I would expect to see the controller in the API project, but we find it in the Application project. 

Thanks!

**Comment by asindarov** [comment]
Hi @karoldeland, I think that's because of Vertical Slice Architecture. I recommend to read about this architecture. I recommend https://www.jimmybogard.com/vertical-slice-architecture/ blog post. There are plenty blog posts about that though

**Comment by nadirbad** [comment]
Hi @karoldeland, the reasoning here was to showcase this solution as possible approach and example. The Application project is core project that contains all the Features. Within a particular Feature in this example we contain all the code necessary controller, DTOs, queries/commands and handlers for that vertical slice. 
Api project is just a top layer, a web host and in this example asp.net core that doesn't contain any controllers or entry points to features, but just the middleware and wiring necessary things.

I hope this helps in clarification, and as I said this just a one way of structuring, there are no strict rules applied. Here is a good video from Derek Comartin about some [VSA misconceptions](https://youtu.be/TfMArQnepco?si=7-81enkcS6bn8-v8)
